// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {platform} from '../models';

export function Activity():Promise<Array<app.RunRecord>>;

export function AddSource(arg1:string):Promise<app.SourceState>;

export function AddSourceAs(arg1:string,arg2:string,arg3:string):Promise<app.SourceState>;

export function BackupNow(arg1:Array<string>,arg2:boolean):Promise<string>;

export function BreakLock():Promise<void>;

export function Browse(arg1:string,arg2:string,arg3:string):Promise<app.BrowseResult>;

export function Cancel():Promise<void>;

export function CheckBackups():Promise<string>;

export function ChooseFolder(arg1:string,arg2:string):Promise<string>;

export function ConfirmPlan(arg1:boolean):Promise<void>;

export function DismissJob():Promise<void>;

export function DismissNotice():Promise<void>;

export function Drives():Promise<Array<platform.Volume>>;

export function ExportReport(arg1:string):Promise<string>;

export function ForgetVault(arg1:string):Promise<void>;

export function GetState():Promise<app.State>;

export function ListBackups():Promise<Array<app.BackupSource>>;

export function Lock():Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function Pause():Promise<void>;

export function RemoveSource(arg1:string):Promise<void>;

export function RenameSource(arg1:string,arg2:string):Promise<void>;

export function Restore(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function Resume():Promise<void>;

export function SetAutomation(arg1:boolean,arg2:string):Promise<void>;

export function SetConfirmBeforeRun(arg1:boolean):Promise<void>;

export function SetExcludes(arg1:Array<string>):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetRetention(arg1:number,arg2:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SuggestRestoreFolder(arg1:string,arg2:string):Promise<string>;

export function SwitchVault(arg1:string):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UseVaultFolder(arg1:string,arg2:string):Promise<app.VaultState>;
